---
- name: Deploy WordPress in AWS cloud
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - amazon.aws
    - community.aws
  roles:
    - { role: aws_wp, infra_state: present }