---
- name: Destroy lab infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - amazon.aws
    - community.aws
  roles:
    - { role: wp, infra_state: absent }