#!/bin/bash

apt-get update

# Bring up NFS
apt-get -y install nfs-common
mkdir -p {{ www_html_dir }}
echo -n {{ efs.efs.filesystem_address }} {{ www_html_dir }} >> /etc/fstab
echo -n ' nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,' >> /etc/fstab
echo    'hard,timeo=600,retrans=2,noresvport 0 0' >> /etc/fstab
mount {{ www_html_dir }}

# Install other required software
apt-get -y install apache2
rm -f {{ www_html_dir }}/index.html
apt-get -y install default-mysql-client
apt-get -y install php php-mysql php-gd
curl -sO https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
mv wp-cli.phar /usr/local/bin/wp
chmod 0755 /usr/local/bin/wp

# If WordPress is already installed, do nothing else
test -f {{ www_html_dir }}/wp-config.php && exit 0
# If other instance is already installing WP, let it go
test -f {{ www_html_dir }}/wp_install_in_progress && exit 0

# Otherwise install WP
touch {{ www_html_dir }}/wp_install_in_progress
mysql -h {{ rds_instance.endpoint.address }} \
      -u {{ rds_username }} \
      -p{{ rds_password }} <<EOF
CREATE USER IF NOT EXISTS '{{ wp_dbuser }}' IDENTIFIED BY '{{ wp_dbpassword }}';
CREATE DATABASE IF NOT EXISTS {{ wp_dbname }};
GRANT ALL PRIVILEGES on {{ wp_dbname }}.* TO '{{ wp_dbuser }}' ;
FLUSH PRIVILEGES;
EOF

chown -R www-data:www-data {{ www_html_dir }}
cd {{ www_html_dir }}
sudo -u www-data wp core download
sudo -u www-data wp config create \
     --dbname={{ wp_dbname }} \
     --dbuser={{ wp_dbuser }}  \
     --dbpass={{ wp_dbpassword }}  \
     --dbhost={{ rds_instance.endpoint.address }}
sudo -u www-data wp core install \
     --url={{ elb.dns_name }} \
     --title="{{ wp_site_title }}" \
     --admin_user={{ wp_admin_user }} \
     --admin_password={{ wp_admin_password }} \
     --admin_email={{ wp_admin_email }}

# Remove semaphore file
rm -f {{ www_html_dir }}/wp_install_in_progress